# kubernetes/03-storage.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce # Can be mounted by one node at a time
  resources:
    requests:
      storage: 1Gi # Request 1 Gigabyte (adjust as needed)
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi # Request 500 Megabytes (adjust as needed)
