# kubernetes/07-backend.yaml
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
spec:
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app: backend
  type: ClusterIP # <-- Change from NodePort to ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1 # Start with one, HPA will manage this
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            # ... (Your existing env vars from ConfigMap and Secret) ...
            - name: POSTGRES_USER
              valueFrom:
                { configMapKeyRef: { name: app-config, key: POSTGRES_USER } }
            - name: POSTGRES_DB
              valueFrom:
                { configMapKeyRef: { name: app-config, key: POSTGRES_DB } }
            - name: POSTGRES_HOST
              valueFrom:
                { configMapKeyRef: { name: app-config, key: POSTGRES_HOST } }
            - name: POSTGRES_PORT
              valueFrom:
                { configMapKeyRef: { name: app-config, key: POSTGRES_PORT } }
            - name: POSTGRES_PASSWORD
              valueFrom:
                {
                  secretKeyRef:
                    { name: postgres-secret, key: POSTGRES_PASSWORD },
                }
            - name: REDIS_HOST
              valueFrom:
                { configMapKeyRef: { name: app-config, key: REDIS_HOST } }
            - name: REDIS_PORT
              valueFrom:
                { configMapKeyRef: { name: app-config, key: REDIS_PORT } }
            - name: REDIS_DB
              valueFrom:
                { configMapKeyRef: { name: app-config, key: REDIS_DB } }
            - name: ML_SERVICE_URL
              valueFrom:
                { configMapKeyRef: { name: app-config, key: ML_SERVICE_URL } }
          # --- Add this section for Autoscaling ---
          resources:
            requests: # <-- HPA needs this!
              cpu: "100m" # Request 0.1 CPU core
              memory: "128Mi" # Request 128 MiB Memory
            limits: # Optional but recommended
              cpu: "500m" # Limit to 0.5 CPU core
              memory: "512Mi" # Limit to 512 MiB Memory
